services:
  nexus:
    build:
      context: .
      dockerfile: nexus/Dockerfile
    ports:
      - "8080:8080"

  consumer:
    build:
      context: .
      dockerfile: consumer/Dockerfile
    depends_on:
      - nexus
    environment:
      - NEXUS_URL=http://nexus:8080
